package com.rejown.qrcraft.presentation.settings

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import com.rejown.qrcraft.BuildConfig

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SettingsScreen(
    navController: NavController,
    modifier: Modifier = Modifier
) {
    var hapticFeedbackEnabled by remember { mutableStateOf(true) }
    var autoSaveScans by remember { mutableStateOf(true) }
    var autoSaveGenerated by remember { mutableStateOf(true) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Settings") },
                navigationIcon = {
                    IconButton(onClick = { navController.navigateUp() }) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back"
                        )
                    }
                }
            )
        },
        modifier = modifier
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            // General Section
            SettingsSectionTitle("General")

            SettingsCard {
                SettingsItem(
                    title = "Haptic Feedback",
                    description = "Vibration on interactions",
                    checked = hapticFeedbackEnabled,
                    onCheckedChange = { hapticFeedbackEnabled = it }
                )
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Scanner Section
            SettingsSectionTitle("Scanner")

            SettingsCard {
                SettingsItem(
                    title = "Auto-save Scans",
                    description = "Automatically save all scanned codes",
                    checked = autoSaveScans,
                    onCheckedChange = { autoSaveScans = it }
                )
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Generator Section
            SettingsSectionTitle("Generator")

            SettingsCard {
                SettingsItem(
                    title = "Auto-save Generated Codes",
                    description = "Automatically save all generated codes",
                    checked = autoSaveGenerated,
                    onCheckedChange = { autoSaveGenerated = it }
                )
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Data Section
            SettingsSectionTitle("Data")

            SettingsCard {
                SettingsClickableItem(
                    title = "Clear Scan History",
                    description = "Delete all scanned codes",
                    onClick = { /* TODO: Implement clear scan history */ }
                )

                HorizontalDivider()

                SettingsClickableItem(
                    title = "Clear Generated History",
                    description = "Delete all generated codes",
                    onClick = { /* TODO: Implement clear generated history */ }
                )

                HorizontalDivider()

                SettingsClickableItem(
                    title = "Clear All Data",
                    description = "Delete all history and settings",
                    onClick = { /* TODO: Implement clear all data */ }
                )
            }

            Spacer(modifier = Modifier.height(24.dp))

            // About Section
            SettingsSectionTitle("About")

            SettingsCard {
                SettingsInfoItem(
                    title = "Version",
                    value = BuildConfig.VERSION_NAME
                )

                HorizontalDivider()

                SettingsClickableItem(
                    title = "Privacy Policy",
                    description = "View our privacy policy",
                    onClick = { /* TODO: Open privacy policy */ }
                )

                HorizontalDivider()

                SettingsClickableItem(
                    title = "Open Source Licenses",
                    description = "View third-party licenses",
                    onClick = { /* TODO: Show licenses */ }
                )

                HorizontalDivider()

                SettingsClickableItem(
                    title = "Rate on Play Store",
                    description = "Help us by rating the app",
                    onClick = { /* TODO: Open Play Store */ }
                )
            }

            Spacer(modifier = Modifier.height(16.dp))
        }
    }
}

@Composable
private fun SettingsSectionTitle(title: String) {
    Text(
        text = title,
        style = MaterialTheme.typography.titleSmall,
        color = MaterialTheme.colorScheme.primary,
        modifier = Modifier.padding(start = 8.dp, bottom = 8.dp)
    )
}

@Composable
private fun SettingsCard(content: @Composable () -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceVariant
        )
    ) {
        Column {
            content()
        }
    }
}

@Composable
private fun SettingsItem(
    title: String,
    description: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { onCheckedChange(!checked) }
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Column(
            modifier = Modifier.weight(1f)
        ) {
            Text(
                text = title,
                style = MaterialTheme.typography.bodyLarge
            )
            Text(
                text = description,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
        Spacer(modifier = Modifier.width(16.dp))
        Switch(
            checked = checked,
            onCheckedChange = onCheckedChange
        )
    }
}

@Composable
private fun SettingsClickableItem(
    title: String,
    description: String,
    onClick: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick)
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Column(
            modifier = Modifier.weight(1f)
        ) {
            Text(
                text = title,
                style = MaterialTheme.typography.bodyLarge
            )
            Text(
                text = description,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }
}

@Composable
private fun SettingsInfoItem(
    title: String,
    value: String
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(
            text = title,
            style = MaterialTheme.typography.bodyLarge,
            modifier = Modifier.weight(1f)
        )
        Text(
            text = value,
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
    }
}
